### ISSUE TITLE
[BUG] Crash when reading Snappy-compressed Parquet v2 file

### ISSUE THREAD

**Issue by Matt711** [rapidsai/cudf#18472]
**Describe the bug**
cuDF crashes during decompression when reading a Parquet file containing a Snappy-compressed data Page V2 with  no actual values.

This occurs in the decompression logic in `reader_impl_chunking.cu` when processing the file via `pl.collect(engine="gpu")`.

**Steps/Code to reproduce bug**
```python
import polars as pl

pl.scan_parquet("empty_datapage_v2.snappy.parquet").collect(engine="gpu")
```
```
ComputeError: RuntimeError: CUDF failure at: /home/coder/cudf/cpp/src/io/parquet/reader_impl_chunking.cu:955: Error during decompression
```

**Expected behavior**
```python
 pl.scan_parquet("empty_datapage_v2.snappy.parquet").collect()
Out[4]: 
shape: (1, 1)
┌───────┐
│ value │
│ ---   │
│ f32   │
╞═══════╡
│ null  │
└───────┘
```

**Additional context**
Here is the parquet file: https://github.com/pola-rs/polars/blob/075fe6134ef0355ad9613da2badd126c95634aaa/py-polars/tests/unit/io/files/empty_datapage_v2.snappy.parquet
Here is the parquet file's metadata
```python
import pylibcudf as plc

meta = plc.io.parquet_metadata.read_parquet_metadata(plc.io.SourceInfo(["empty_datapage_v2.snappy.parquet"]))

print("\nFile metadata:")
print(meta.metadata())

print("\nNumber of row groups:")
print(meta.num_rowgroups())

print("\nTotal number of rows:")
print(meta.num_rows())

print("\nRow group metadata:")
print(meta.rowgroup_metadata())

print("\nSchema root name:")
schema = meta.schema()
print(schema.root().name()) 

```
```
File metadata:
{'org.apache.spark.sql.parquet.row.metadata': '{"type":"struct","fields":[{"name":"value","type":"float","nullable":true,"metadata":{}}]}', 'org.apache.spark.version': '3.5.5'}

Number of row groups:
1

Total number of rows:
1

Row group metadata:
[{'total_byte_size': 23, 'num_rows': 1}]

Schema root name:
spark_schema
```

And here's more complete metadata
```python
import pyarrow.parquet as pq

pq_file = pq.ParquetFile("empty_datapage_v2.snappy.parquet")
print(pq_file.metadata)
print(pq_file.metadata.row_group(0).column(0))
```
```
<pyarrow._parquet.FileMetaData object at 0x79859f19aa70>
  created_by: parquet-mr version 1.13.1 (build db4183109d5b734ec5930d870cdae161e408ddba)
  num_columns: 1
  num_rows: 1
  num_row_groups: 1
  format_version: 1.0
  serialized_size: 353
<pyarrow._parquet.ColumnChunkMetaData object at 0x79859a1781d0>
  file_offset: 4
  file_path: 
  physical_type: FLOAT
  num_values: 1
  path_in_schema: value
  is_stats_set: True
  statistics:
    <pyarrow._parquet.Statistics object at 0x79859a178040>
      has_min_max: False
      min: None
      max: None
      null_count: 1
      distinct_count: None
      num_values: 0
      physical_type: FLOAT
      logical_type: None
      converted_type (legacy): NONE
  compression: SNAPPY
  encodings: ('PLAIN',)
  has_dictionary_page: False
  dictionary_page_offset: None
  data_page_offset: 4
  total_compressed_size: 23
  total_uncompressed_size: 23
```
